"""
Django settings for pureBeurreOC project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: keep the secret key used in production secret!
if os.environ.get('ENV') == 'PRODUCTION':
    DEBUG = False

    # Static files settings
    PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
    STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')

    # Extra places for collectstatic to find static files.
    STATICFILES_DIRS = (
        os.path.join(PROJECT_ROOT, 'static'),
    )
else:
    DEBUG = True
    SECRET_KEY = '%!p7ld+l#wxdmmo4u(7@swrvap*$05wom^6!q-flp$w+2#%$t-'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'guuzii-purbeurre.herokuapp.com'
]
LOGIN_REDIRECT_URL = '/products/'


# Application definition

INSTALLED_APPS = [
    'products.apps.ProductsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

if os.environ.get('ENV') == 'PRODUCTION':
    # ...
    # Simplified static file serving.
    # https://warehouse.python.org/project/whitenoise/
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'pureBeurreOC.urls'
INTERNAL_IPS = ['127.0.0.1']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pureBeurreOC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'PurBeurre',
        'USER': 'postgres',
        'PASSWORD': 'J4sp4r075',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
    'prod': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dbge11up3pb3jn',
        'USER': 'juyqbuocdbzhth',
        'PASSWORD': 'bc1d9a412abc1082d76969ada51138b20d20acbceb1b037668e449e4872e1ff3',
        'HOST': 'ec2-54-165-36-134.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}

if os.environ.get('ENV') == 'PRODUCTION':
    db_from_env = dj_database_url.config(conn_max_age=500)
    DATABASES['prod'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# Open Food Facts API requests variables

USER_AGENT_OFF = "Pur Beurre Django - Projet étudiant - Python - Version 3.7.3"

NB_PRODUCTS_TO_GET = 100

PRODUCTS_CATEGORIES = {
    "plant-based-foods": "Fruits, Légumes, Plantes",
    "cereals-and-potatoes": "Féculents",
    "meats": "Viandes",
    "fishes": "Poissons",
    "desserts": "Desserts",
    "beverages": "Boissons"
}

NUTRIMENTS = {
    "fat": {
        "name": "matières grasses / lipides",
        "unit": "g"
    },
    "saturated-fat": {
        "name": "acide gras saturés",
        "unit": "g"
    },
    "sugars": {
        "name": "sucres",
        "unit": "g"
    },
    "salt": {
        "name": "sel",
        "unit": "g"
    }
}
