# Generated by Django 3.0.5 on 2020-04-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productnutriments',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
